services:
  ceo-gateway:
    extends:
      file: ../docker-compose.logger.override.yml
      service: logger
    volumes:  # To allow dynamic reloading in dev
      - ${SEPAL_PROJECT_DIR}/lib/js/shared:/usr/local/src/sepal/lib/js/shared
      - ${SEPAL_PROJECT_DIR}/modules/ceo-gateway:/usr/local/src/sepal/modules/ceo-gateway
