services:
  # scene-metadata-redis:
  #   extends:
  #     file: ../docker-compose.logger.yml
  #     service: logger
  #   image: "redis:6"
  #   container_name: scene-metadata-redis
  #   volumes:
  #     - "${SEPAL_DATA_DIR}/scene-metadata-redis:/data"
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  #     timeout: 60s
  #     interval: 1s
  #     retries: 60
  #   networks:
  #     - sepal
  #   restart: always

  scene-metadata:
    extends:
      file: ../docker-compose.logger.yml
      service: logger
    build:
      context: ../..
      dockerfile: ./modules/scene-metadata/Dockerfile
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
    image: "${DOCKER_REGISTRY_HOST:-localhost}/openforis/scene-metadata:${SEPAL_VERSION:-latest}"
    container_name: scene-metadata
    init: true
    volumes:
      - "${SEPAL_DATA_DIR}/sepal/home:/sepalUsers"
    environment:
      DEPLOY_ENVIRONMENT: "${DEPLOY_ENVIRONMENT}"
      POLL_INTERVAL_MS: "3600000"
    networks:
      - sepal
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      timeout: 60s
      interval: 1s
      retries: 60
    restart: always
    ulimits:
      core: 0

networks:
  sepal:
    external: true
